### ISSUE TITLE
Incorrect description of articles

### ISSUE THREAD

**Issue by ChristRm** [exyte/ReadabilityKit#12]
Try to load articles
"http://www.jobsnhire.com/articles/35030/20160214/need-know-cvs-health.htm"
"http://www.bbc.com/news/world-asia-china-37081013"  
"http://www.bbc.com/culture/story/20160805-when-shocking-images-must-be-covered-up"
"http://football.ua/germany/311510-podolski-zavershil-kareru-v-sbornojj.html"

using code
        let sURL = "http://football.ua/germany/311510-podolski-zavershil-kareru-v-sbornojj.html"
        let articleUrl = NSURL(string: sURL)

```
    let parser = Readability(url: articleUrl!)

    let title = parser.title()
    let description = parser.description()
    let keywords = parser.keywords()
    let imageUrl = parser.topImage()
    let videoUrl = parser.topVideo()
```

For all this articles parser.description() returns only their first paragraph.

**Comment by zapletnev** [comment]
Thanks for reporting and testing. We will check these URLs as soon as possible!

**Comment by zapletnev** [comment]
@ChristRm I checked following URLs and please let me share my thoughts on this. ReadabilityKit extracts preview of the article, it doesn't provide the full text of the article (as do our [snacktory](https://github.com/karussell/snacktory), [newspaper](https://github.com/codelucas/newspaper)). Readability.description displays only preview text of the URL.

I have created separate task "Provide the full text of the article" #13.

**Comment by ChristRm** [comment]
Thanks for responce. There is no pod for iOs app for providing reader mode like in Safari, so this feature will be helpful.
