### ISSUE TITLE
Employ asynchronous patterns

### ISSUE THREAD

**Issue by robertmryan** [exyte/ReadabilityKit#14]
I would suggest that this code excise its use of dispatch semaphores to make the fundamentally asynchronous `NSURLSession` behave synchronously. Apple made this asynchronous for a reason.

If a user accidentally called this from the main thread, you'd block the main thread, which results in behaviors ranging from a poor UX to an app possibly getting killed by the watchdog process. Worse, if a user called this from within their own `NSURLSession` completion handler (e.g. http://stackoverflow.com/q/39253599/1271826), this will deadlock their code.

I'd also suggest that you not initiate the asynchronous method from within the `init` method. By convention, one should generally configure the object from within `init`, and then have a separate method to start the process.

**Comment by vhailor13** [comment]
Closed by mistake. Work in progress.

**Comment by vhailor13** [comment]
Thanks for your contribution. Yes, we decided to remove sync API and now only async API is available:

```
Readability.parse(url: NSUrl, { data in
  // use parsed data here
})
```
