### ISSUE TITLE
iOS 10 App Transport Security

### ISSUE THREAD

**Issue by danielrhodes** [exyte/ReadabilityKit#15]
In iOS 10, Apple has promised to turn off ATS for developers who want to submit to the App Store. In this scenario, what are the plans to support this?

**Comment by vhailor13** [comment]
Closed by mistake. Work in progress.

**Comment by zapletnev** [comment]
@danielrhodes yes, ATS will be required for all applications in January 2017. And your application will not be able to provide a relevant preview for HTTP sites with ReadabilityKit. Unfortunately, we can't do anything here; this is Apple politics. We have plans to deploy ReadabilityKit on the public server with https support and make the corresponding API for accessing ReadabilityKit.
