### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by danielrhodes** [exyte/ReadabilityKit#16]
Is this in the works? What can I do to help?

**Comment by zapletnev** [comment]
@danielrhodes thanks for reporting. Yes, we have a plans to add a separate branch for swift3 but didn't start it yet. We welcome your contributions if you would like to help us!

**Comment by xmollv** [comment]
I'm also interested in the 3.0 migration. I'm starting a side project right now and I was planing to use it with Swift 3 🚀

**Comment by zapletnev** [comment]
@xmollv thanks for your interest! Right now the only one thing that blocking us is Ji migration: https://github.com/honghaoz/Ji/issues/32

**Comment by honghaoz** [comment]
@zapletnev Just updated! Try `pod 'Ji', '~> 2.0.0'`

**Comment by zapletnev** [comment]
@honghaoz @xmollv awesome! When we will take care about ReadabilityKit swift 3 support today 🚀 🚀 🚀

**Comment by vhailor13** [comment]
Swift 3.0 support is available now!
