### ISSUE TITLE
Initializer for conditional binding

### ISSUE THREAD

**Issue by a75c6** [exyte/ReadabilityKit#18]
Building example and get error:

Initializer for conditional binding must have Optional type, not 'String'

From Readability+Networking.swift:

 guard let urlStr = url.absoluteString else {
                        return
                    }

Can change to the following to fix:

let urlStr = url.absoluteString

Thanks.

**Comment by vhailor13** [comment]
Thanks for report! Solved for swift 2.2 in **master**.
Swift 2.3 version can be found in **swift_2.3** branch.
