### ISSUE TITLE
Swift 3 Help

### ISSUE THREAD

**Issue by kerbelda** [exyte/ReadabilityKit#19]
Ji.swift and JiNode.swift are both broken in swift 3. Can't figure out how to fix them with things like "openlass", "fileprifilevate", opeoppened" etc.

**Comment by vhailor13** [comment]
Hello, Dan! You can find swift 3.0 version of Ji here https://github.com/honghaoz/Ji/releases
Also ReadabilityKit already updated for Swift 3.0

**Comment by zapletnev** [comment]
@kerbelda please let us know if still have any issues with it. For now, I will close this issue.

**Comment by kerbelda** [comment]
I installed the Cocoapod on my existing project and still get tons of compile errors in both ReadabilityKit (6.0.0) and Ji (2.0.0). I'm not sure what I'm doing wrong here. Here's an [example](http://imgur.com/a/6hHxv) of the errors I'm getting.

**Comment by vhailor13** [comment]
It seems your project target have not swift 3.0 support enabled, check 
"User Legacy Swift Language Version" settings flag.
Here is manual install example
[Example.zip](https://github.com/exyte/ReadabilityKit/files/505944/Example.zip)
