### ISSUE TITLE
Get html content like Reader Mode in Safari

### ISSUE THREAD

**Issue by minas90** [exyte/ReadabilityKit#21]
Hi there,
Is it possible to get not just a plain text, but html of extracted article including images and videos?

**Comment by vhailor13** [comment]
Hello @minas90 ,
There is no such logic available, I can create a separate branch for you to test. And add logic to extract HTML content of node with maximum "weight"

**Comment by minas90** [comment]
Hi,
It will be great! 
Let me know how I can help. I modified boilerpipe ( Java ) to extract article by keeping html structure and appropriate images / videos within it. It works amazing on my Android app, now I'm working on iOS version and need the same functionality. Don't have much experience with readability, but Apple's version somehow manages to work pretty well other than it fails to handle articles with multiple photos and videos at the same time.

For example test this article in Safari's Reader mode
http://blognews.am/arm/news/435289/orva-baxadratomsy-shokolade-sendvich.html

And these examples with a lot of photos and videos which safari failed to handle

http://blognews.am/arm/news/435251/uxxatir-jakuzi-khohanoc%E2%80%A4-nerkayacvel-e-amenafantastik-avtobusy-lusankarner-tesanyut.html

http://blognews.am/arm/news/435249/20-milion-kankhik-gumar-nerqnaki-tak-photo-video.html

**Comment by vhailor13** [comment]
It seems like there is no fast way to generate good looking HTML page in a current state of the library. But we can use your ideas to generate HTML page using _boilerpipe_ in our lib.

**Comment by minas90** [comment]
boilerpipe is in Java and kind of tricky to convert it to swift or Obj C, I already tried. It should be fully rewritten which will take a lot of time.

**Comment by demostars** [comment]
@minas90 Great job. How did you use boilerpipe in Android App? Any article about this? Thanks.

**Comment by zapletnev** [comment]
ReadabilityKit project switched to the maintenance mode and we recommend to use SwiftLinkPreview in the new code.
