### ISSUE TITLE
Issue with Linkedin url 

### ISSUE THREAD

**Issue by AashishNagar** [exyte/ReadabilityKit#23]
library not working with url "https://www.linkedin.com". Image not coming.

**Comment by atbrennan** [comment]
i've also been having trouble with youtube links. no image or video and no description.

**Comment by zapletnev** [comment]
Hi @AashishNagar,

Thanks for reporting and sorry for response delay.

I just tried next LinkedIn URL, and everything works fine on my side:
https://www.linkedin.com/feed/update/urn:li:activity:6341926280803471360

I will close this ticket for now. If you still can reproduce this issue, please reopen the ticket and attach the URL.
