### ISSUE TITLE
Issues using library in Objective-C code

### ISSUE THREAD

**Issue by haris008** [exyte/ReadabilityKit#25]
podfile
   use_frameworks!
   pod 'ReadabilityKit'

Unable to call [Readability parse] ...

**Comment by zapletnev** [comment]
Hi @haris008,
We are working on swift 4 release. It should be available on this or next week.

**Comment by rpyn** [comment]
It currently does not seem to be working (2017/10/15). The error still says 
XPath error : Invalid expression
XPath error : Invalid expression
XPath error : Invalid expression
XPath error : Invalid expression
XPath error : Invalid predicate
XPath error : Invalid expression
XPath error : Invalid predicate
XPath error : Invalid expression

Thanks

**Comment by vhailor13** [comment]
@ryyyhy Finally fixed those issues in new release. You can get it via:
pod 'ReadabilityKit', '0.7.0'
