### ISSUE TITLE
Adding date extraction feature

### ISSUE THREAD

**Issue by hayetech** [exyte/ReadabilityKit#27]
Any ideas to how to parse date from the article?

**Comment by zapletnev** [comment]
Hi @hayetech,
Unfortunately, ReadabilityKit doesn't support date extraction. But you can easily extend parser here:
https://github.com/exyte/ReadabilityKit/blob/master/Sources/Readability.swift#L485

Here you have whole dom element loaded. ReadibilityKit using Ji for XML parsing: https://github.com/honghaoz/Ji

**Comment by hayetech** [comment]
Thanks working on it, will update when it's done.
