### ISSUE TITLE
Carthage: error: module compiled with Swift 4.0 cannot be imported in Swift 4.0.2

### ISSUE THREAD

**Issue by samuraisam** [exyte/ReadabilityKit#28]
Running `carthage update` fails on the most recent version of Xcode.

```
error: module compiled with Swift 4.0 cannot be imported in Swift 4.0.2: /Users/sam/Documents/dev/DispatchApp/Carthage/Checkouts/ReadabilityKit/Dependencies/iOS/Ji.framework/Modules/Ji.swiftmodule/arm64.swiftmodule
```

```Xcode 9.1
Build version 9B55
```

I'm happy to submit a PR to fix, but I'm unsure how to get the libraries from the Ji project.

**Comment by vhailor13** [comment]
Made fast fix for carthage, you can use it via "github "exyte/ReadabilityKit" ~> 0.7.2". Will remove warnings later.
