### ISSUE TITLE
Twitter and Youtube not been parsed

### ISSUE THREAD

**Issue by hayetech** [exyte/ReadabilityKit#29]
Hi,

In the initial testing of this Kit, I found out that it is unable to find parse the any data from the following,

- Twitter

- Youtube

Any ideas, as to what would be causing this issue, would be helpful.
Thanks.

**Comment by zapletnev** [comment]
Hi,

Thanks for reporting. Sorry for the delayed response. I tried twitter and it works for me:

**URL**: https://twitter.com/NASA/status/944034008459022336
**Title**: NASA on Twitter: “It’s rare for large wildfires to burn in CA in Dec., but the #ThomasFire shattered most records after burning for 16 days &amp; scorching 272,00”
**Description**: It’s rare for large wildfires to burn in CA in Dec., but the #ThomasFire shattered most records after burning for 16 days &amp;amp; scorching 272,000 acres. This image uses @NASAEarth satellite data &amp;amp; a Global Digital Elevation Model to show topography of the area https://t.co/5VGgEQHN8y
**Image**: https://pbs.twimg.com/media/DRnh7OcX0AAzXMA.jpg

Youtube changed their page structure and removed all meta tags. And now Youtube pages can't be appropriately parsed with existing algorithm.  

ReadabilityKit project switched to the maintenance mode and we recommend to use [SwiftLinkPreview](https://github.com/LeonardoCardoso/SwiftLinkPreview) in the new code.
