### ISSUE TITLE
Some URLS are not parsed.

### ISSUE THREAD

**Issue by HackShitUp** [exyte/ReadabilityKit#30]
Some URLS are not parsed? It's either that or the URLSession request takes quite long to parse the data. Is there a way to improve its speed/performance?

**Comment by zapletnev** [comment]
Hi @HackShitUp,

Sorry for the response delay.

To improve performance you can implement a cache on the application side and use ReadabilityKit parser directly:
https://github.com/exyte/ReadabilityKit/blob/master/Sources/Readability.swift#L480

As a parameter, it is using raw HTML data.

Also, we have an async API that you can use:
https://github.com/exyte/ReadabilityKit/blob/master/Sources/Readability%2BAsync.swift#L27

Thanks for using ReadabilityKit!
