### ISSUE TITLE
cannot parse certain websites 

### ISSUE THREAD

**Issue by Yashraj4394** [exyte/ReadabilityKit#38]
" https://economictimes.indiatimes.com/tech/hardware/the-iphone-se-is-in-india-heres-all-we-know/not-a-flagship/slideshow/76280131.cms "

I have implemented this pod in my project. But it seems to not parse the url's that end with ".cms". 

![Simulator Screen Shot - iPhone X - 2020-06-10 at 10 00 42](https://user-images.githubusercontent.com/42212959/84227313-b51b3e80-ab01-11ea-814b-aca88d449e45.jpg)

**Comment by shipinev** [comment]
Hey @Yashraj4394.
Could you please provide more information about how you work with ReadabilityKit?

I tried to check the URL you provided, and it works for me. Markup of this page is a bit specific due to card-like presentation, but still, it's possible to obtain some data.

```swift
guard let url = URL(string: "https://economictimes.indiatimes.com/tech/hardware/the-iphone-se-is-in-india-heres-all-we-know/not-a-flagship/slideshow/76280131.cms") else {
    return
}
Readability.parse(url: url) { data in
    dump(data)
}
```

```
▿ ReadabilityKit.ReadabilityData
  - title: "The iPhone SE is in India, here\'s all we know - ​Not a flagship | The Economic Times"
  ▿ description: Optional("The latest iPhone from Apple is not what you would expect - a successor to the 2016 SE - it is designed to look like the iPhone 8 from 2017, but is a massive upgrade on it.Image credit: www.apple.com/in/ ​Not a flagship")
  ▿ topImage: Optional("https://img.etimg.com/thumb/msid-76280131,width-1070,height-580,overlay-economictimes/photo.jpg")
  ▿ text: Optional("\n  ENGLISHहिन्दीET APPSFOLLOW USFACEBOOKTWITTERYOUTUBELINKEDININSTAGRAMFLIPBOARDPINTERESTRSSHomeMFNRI and GadgetsBusiness ››› ET Online|1/5The latest iPhone from Apple is not what you would expect - a successor to the 2016 SE - it is designed to look like the iPhone 8 from 2017, but is a massive upgrade on it...")
  ▿ keywords: Optional([])
  ▿ datePublished: Optional("09 Jun 2020")
```

**Comment by shipinev** [comment]
@Yashraj4394 I hope the issue resolved for you. Do not hesitate to reopen this issue if you have any further questions.
