### ISSUE TITLE
Error when trying to add with SPM

### ISSUE THREAD

**Issue by eldare** [exyte/ReadabilityKit#41]
Trying to add with SPM, getting the following error: `git@github.com:exyte/ReadabilityKit.git has no Package.swift manifest for version 0.7.4`

**Comment by morissonmaciel** [comment]
This error could be related to wrong Swift Package manifest file: https://github.com/exyte/ReadabilityKit/issues/42
There is a typo preventing from importing.

**Comment by morissonmaciel** [comment]
PR #43 opened with the fix

**Comment by f3dm76** [comment]
Hey @eldare and @morissonmaciel, thank you for bringing this to our attention, the PR @morissonmaciel opened is merged now, have a great day guys!
