### ISSUE TITLE
GIF

### ISSUE THREAD

**Issue by lfarah** [exyte/ReadabilityKit#5]
I'd be cool to show a GIF or an Image showing the power of **ReadabilityKit**

**Comment by zapletnev** [comment]
@lfarah thanks for your suggestions but we think that GIFs are more useful for UI libraries. Can you give some GIFs examples for core libraries such as ReadabilityKit?

**Comment by lfarah** [comment]
We could have a screenshot like [URL Preview](https://github.com/itsmeichigo/URLPreview) does.
I was imagining a GIF that shows a textfield with an URL and after pressing return, it loads the page's snippet

**Comment by zapletnev** [comment]
@lfarah sounds good 👍, let me see what we can do!

**Comment by lfarah** [comment]
Good job! 👏 👏 👏 👏 👏 👏
