### ISSUE TITLE
Wrong instructions for manual installation

### ISSUE THREAD

**Issue by zapletnev** [exyte/ReadabilityKit#6]
Commit: 84cadfc2c659d0ce442e9349174f9b890bf77c70
Author: @lfarah

It isn't enough to copy ReadabilityKit.swift into your project since we have third-party dependency to XML parser `Ji`.

**Comment by lfarah** [comment]
Yeah, it makes sense.
What do you think about this?

#### Manually
1. Download and drop `ReadabilityKit.swift` in your project.  
2. Install [Ji  XML parser](https://github.com/honghaoz/Ji)
3. Congratulations

**Comment by vhailor13** [comment]
Seems fine, Ji XML parser has manual instruction to help.

**Comment by zapletnev** [comment]
@lfarah thanks, fixed!

**Comment by lfarah** [comment]
Awesome! I'm glad it worked out 😄
